In [41]:
from transformers.models.llama.modeling_llama import LlamaForCausalLM
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM2-135M")
model = LlamaForCausalLM.from_pretrained("HuggingFaceTB/SmolLM2-135M")

In [ ]:
import torch

input_ids = torch.concat((torch.arange(10, dtype=torch.int64),torch.Tensor([6,47224])),dim=-1).view(1, -1).to(torch.int64)
print(input_ids)
result = model(input_ids=input_ids)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 6]])


In [47]:
print(torch.argmax(result.logits, dim=-1))

tensor([[  504,    28,   198,   198,   198,     3,    79,     6,     6,     6,
         47224]])


In [48]:
model.config.pad_token_id = tokenizer.pad_token_id
result=model.generate(input_ids=torch.arange(10).view(1, -1), max_length=20)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


In [ ]:
print(result)

tensor([[    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
             6, 47224, 47224, 47224, 47224, 47224, 47224, 47224, 47224, 47224]])
